[package]
name = "actix-web-musings"
version = "0.1.0"
authors = ["Huston Bokinsky <huston@deepgram.com>"]

[dependencies]
actix-web = { version = "0.7.4", features = ["alpn"] }
futures-await = "0.1.1"
